In [3]:
class StaffMember:
    total_staff = 0

    def __init__(self, first_name, last_name, salary, division):
        self.first_name = first_name
        self.last_name = last_name
        self.salary = salary
        self.division = division
        StaffMember.total_staff += 1

    @classmethod
    def calculate_average_salary(cls, staff_list):
        if not staff_list:
            return 0
        total_salary = sum(staff.salary for staff in staff_list)
        return total_salary / len(staff_list)

    def show_details(self):
        return f"First Name: {self.first_name}, Last Name: {self.last_name}, Salary: {self.salary}, Division: {self.division}"

class PermanentStaff(StaffMember):
    def __init__(self, first_name, last_name, salary, division, perks):
        super().__init__(first_name, last_name, salary, division)
        self.perks = perks

    def show_details(self):
        base_info = super().show_details()
        return f"{base_info}, Perks: {self.perks}"

staff1 = StaffMember(first_name="Arisu", last_name="Leo", salary=55000, division="Engineering")
staff2 = StaffMember(first_name="Usagi", last_name="Zen", salary=62000, division="Marketing")
permanent_staff1 = PermanentStaff(first_name="Momoka", last_name="Jack", salary=75000, division="HR", perks="Medical Coverage")

staff_list = [staff1, staff2, permanent_staff1]

print("Staff Information:")
print(staff1.show_details())
print(staff2.show_details())
print(permanent_staff1.show_details())

print("\nAverage Salary of Staff Members:", StaffMember.calculate_average_salary(staff_list))

print("\nTotal Number of Staff Members:", StaffMember.total_staff)

Staff Information:
First Name: Arisu, Last Name: Leo, Salary: 55000, Division: Engineering
First Name: Usagi, Last Name: Zen, Salary: 62000, Division: Marketing
First Name: Momoka, Last Name: Jack, Salary: 75000, Division: HR, Perks: Medical Coverage

Average Salary of Staff Members: 64000.0

Total Number of Staff Members: 3


In [4]:
import numpy as np
random_vector = np.random.uniform(1, 20, size=20)
reshaped_matrix = random_vector.reshape(4, 5)
max_positions = np.argmax(reshaped_matrix, axis=1)
updated_matrix = reshaped_matrix.copy()
np.put_along_axis(updated_matrix, max_positions[:, None], 0, axis=1)
print("Original Matrix:")
print(reshaped_matrix)
print("\nUpdated Matrix:")
print(updated_matrix)

Original Matrix:
[[ 4.92168706  9.17468545  2.96981241 13.46753979  2.23759615]
 [14.94310319 10.84389907  1.82268206 16.09788231  2.51928939]
 [ 6.11836971 11.93304951 11.20944558 14.57888518 12.53681819]
 [11.3084094  16.07880742  7.14903027  4.52145455  1.67820908]]

Updated Matrix:
[[ 4.92168706  9.17468545  2.96981241  0.          2.23759615]
 [14.94310319 10.84389907  1.82268206  0.          2.51928939]
 [ 6.11836971 11.93304951 11.20944558  0.         12.53681819]
 [11.3084094   0.          7.14903027  4.52145455  1.67820908]]
